-- Starting data for the shift tools, entered from Nathan's PARS.xlsx
-- (Sept 24, 2026) plus the tasks and reminders Andrew described. Only runs
-- into empty tables, so re-applying never duplicates anything. Everything
-- here is editable from the register tablet.

insert into par_items (area, section, name, par_qty, unit, source, sort_order)
select * from (values
  ('Concessions', 'Pizza', 'Pizza crust', 1, 'reserve box', 'Sam''s Club', 10),
  ('Concessions', 'Pizza', 'Cheese', 1, 'reserve', 'Sam''s Club', 20),
  ('Concessions', 'Pizza', 'Pizza sauce', 2, 'reserve', 'Sam''s Club', 30),
  ('Concessions', 'Pizza', 'Garlic seasoning', 0.5, 'shaker', 'Sam''s Club', 40),
  ('Concessions', 'Pizza', 'Italian seasoning', 0.5, 'shaker', 'Sam''s Club', 50),
  ('Concessions', 'Pizza', 'Pepperoni', 1, 'reserve', 'Sam''s Club', 60),
  ('Concessions', 'Popcorn', 'Popcorn kernels', null, null, 'Andrew', 70),
  ('Concessions', 'Popcorn', 'Popping oil', 1, 'reserve', 'Andrew', 80),
  ('Concessions', 'Popcorn', 'Flavacol', 1, 'carton', 'Andrew', 90),
  ('Concessions', 'Hot dogs', 'Hot dogs', 1, 'reserve pack', 'Walmart', 100),
  ('Concessions', 'Hot dogs', 'Hot dog buns', 2, 'sleeves', 'Walmart', 110),
  ('Concessions', 'Nachos', 'Nacho cheese', 1, 'reserve can', 'Walmart', 120),
  ('Concessions', 'Nachos', 'Tortilla chips', 3, 'reserve bags', 'Walmart', 130),
  ('Concessions', 'Candy', 'M&M''s', 5, null, 'Walmart', 140),
  ('Concessions', 'Candy', 'Peanut M&M''s', 5, null, 'Walmart', 150),
  ('Concessions', 'Candy', 'Peanut Butter M&M''s', 5, null, 'Walmart', 160),
  ('Concessions', 'Candy', 'Reese''s Pieces', 5, null, 'Walmart', 170),
  ('Concessions', 'Candy', 'Milk Duds', 5, null, 'Walmart', 180),
  ('Concessions', 'Candy', 'Whoppers', 5, null, 'Walmart', 190),
  ('Concessions', 'Candy', 'Junior Mints', 5, null, 'Walmart', 200),
  ('Concessions', 'Candy', 'Skittles', 5, null, 'Walmart', 210),
  ('Concessions', 'Candy', 'Skittles (Wild Berry)', 5, null, 'Walmart', 220),
  ('Concessions', 'Candy', 'Sour Skittles', 5, null, 'Walmart', 230),
  ('Concessions', 'Candy', 'Nerds Gummy Cluster', 5, null, 'Walmart', 240),
  ('Concessions', 'Candy', 'Sour Patch Kids', 5, null, 'Walmart', 250),
  ('Concessions', 'Candy', 'Swedish Fish', 5, null, 'Walmart', 260),
  ('Concessions', 'Candy', 'SweeTarts Mini Chewy', 5, null, 'Walmart', 270),
  ('Concessions', 'Candy', 'Hot Tamales', 5, null, 'Walmart', 280),
  ('Concessions', 'Candy', 'Mike and Ike (blue)', 5, null, 'Walmart', 290),
  ('Concessions', 'Candy', 'Mike and Ike (green)', 5, null, 'Walmart', 300),
  ('Concessions', 'Cereal', 'Fruity Pebbles', 5, null, 'Walmart', 310),
  ('Concessions', 'Cereal', 'Cocoa Pebbles', 5, null, 'Walmart', 320),
  ('Concessions', 'Cereal', 'Cinnamon Toast Crunch', 5, null, 'Walmart', 330),
  ('Concessions', 'Cereal', 'Apple Jacks', 5, null, 'Walmart', 340),
  ('Concessions', 'Cereal', 'Raisin Bran', 5, null, 'Walmart', 350),
  ('Concessions', 'Cereal', 'Lucky Charms', 5, null, 'Walmart', 360),
  ('Concessions', 'Cereal', 'Frosted Flakes', 5, null, 'Walmart', 370),
  ('Concessions', 'Cereal', 'Cheerios', 5, null, 'Walmart', 380),
  ('Concessions', 'Fountain soda', 'Coke', 1, 'reserve box', 'Ozarks Bottling Co.', 390),
  ('Concessions', 'Fountain soda', 'Diet Coke', 1, 'reserve box', 'Ozarks Bottling Co.', 400),
  ('Concessions', 'Fountain soda', 'Dr Pepper', 1, 'reserve box', 'Ozarks Bottling Co.', 410),
  ('Concessions', 'Fountain soda', 'Diet Dr Pepper', 1, 'reserve box', 'Ozarks Bottling Co.', 420),
  ('Concessions', 'Fountain soda', 'Sprite', 1, 'reserve box', 'Ozarks Bottling Co.', 430),
  ('Concessions', 'Fountain soda', 'Barq''s', 1, 'reserve box', 'Ozarks Bottling Co.', 440),
  ('Concessions', 'Canned soda (outdoor & reserve)', 'Coke', 1, 'reserve 24-pack', 'Sam''s Club', 450),
  ('Concessions', 'Canned soda (outdoor & reserve)', 'Diet Coke', 1, 'reserve 24-pack', 'Sam''s Club', 460),
  ('Concessions', 'Canned soda (outdoor & reserve)', 'Dr Pepper', 1, 'reserve 24-pack', 'Sam''s Club', 470),
  ('Concessions', 'Canned soda (outdoor & reserve)', 'Diet Dr Pepper', 1, 'reserve 24-pack', 'Sam''s Club', 480),
  ('Concessions', 'Canned soda (outdoor & reserve)', 'Sprite', 1, 'reserve 24-pack', 'Sam''s Club', 490),
  ('Concessions', 'Canned soda (outdoor & reserve)', 'Barq''s', 1, 'reserve 24-pack', 'Sam''s Club', 500),
  ('Bar', 'Liquor', 'Well Rum', 2, 'reserve bottles', null, 10),
  ('Bar', 'Liquor', 'Captain Morgan', 2, 'reserve bottles', null, 20),
  ('Bar', 'Liquor', 'Bacardi', 2, 'reserve bottles', null, 30),
  ('Bar', 'Liquor', 'Meyers', 2, 'reserve bottles', null, 40),
  ('Bar', 'Liquor', 'Well Bourbon', 2, 'reserve bottles', null, 50),
  ('Bar', 'Liquor', 'Buffalo Trace', 2, 'reserve bottles', null, 60),
  ('Bar', 'Liquor', 'Woodford Reserve', 2, 'reserve bottles', null, 70),
  ('Bar', 'Liquor', 'Maker''s Mark', 2, 'reserve bottles', null, 80),
  ('Bar', 'Liquor', 'Well Gin', 2, 'reserve bottles', null, 90),
  ('Bar', 'Liquor', 'Tanqueray', 2, 'reserve bottles', null, 100),
  ('Bar', 'Liquor', 'Bombay Sapphire', 2, 'reserve bottles', null, 110),
  ('Bar', 'Liquor', 'Hendricks', 2, 'reserve bottles', null, 120),
  ('Bar', 'Liquor', 'Well Vodka', 2, 'reserve bottles', null, 130),
  ('Bar', 'Liquor', 'Absolut', 2, 'reserve bottles', null, 140),
  ('Bar', 'Liquor', 'Tito''s', 2, 'reserve bottles', null, 150),
  ('Bar', 'Liquor', 'Grey Goose', 2, 'reserve bottles', null, 160),
  ('Bar', 'Liquor', 'Well Whiskey', 2, 'reserve bottles', null, 170),
  ('Bar', 'Liquor', 'Seagram''s Seven', 2, 'reserve bottles', null, 180),
  ('Bar', 'Liquor', 'Crown Royal', 2, 'reserve bottles', null, 190),
  ('Bar', 'Liquor', 'Wild Turkey', 2, 'reserve bottles', null, 200),
  ('Bar', 'Liquor', 'American Honey', 2, 'reserve bottles', null, 210),
  ('Bar', 'Liquor', 'Southern Comfort', 2, 'reserve bottles', null, 220),
  ('Bar', 'Liquor', 'Well Tequila', 2, 'reserve bottles', null, 230),
  ('Bar', 'Liquor', 'Jose Cuervo', null, null, null, 240),
  ('Bar', 'Liquor', 'Patron', 2, 'reserve bottles', null, 250),
  ('Bar', 'Liquor', 'Don Julio', 2, 'reserve bottles', null, 260),
  ('Bar', 'Liqueurs & mixers', 'Rumchata', 2, 'bottles', null, 270),
  ('Bar', 'Liqueurs & mixers', 'Bailey''s', 2, 'bottles', null, 280),
  ('Bar', 'Liqueurs & mixers', 'Di Amore Amaretto', 2, 'bottles', null, 290),
  ('Bar', 'Liqueurs & mixers', 'Triple Sec', 2, 'bottles', null, 300),
  ('Bar', 'Liqueurs & mixers', 'Campari', 2, 'bottles', null, 310),
  ('Bar', 'Liqueurs & mixers', 'Dry Vermouth', 2, 'bottles', null, 320),
  ('Bar', 'Liqueurs & mixers', 'Sweet Vermouth', 2, 'bottles', null, 330),
  ('Bar', 'Liqueurs & mixers', 'Midori', 2, 'bottles', null, 340),
  ('Bar', 'Liqueurs & mixers', 'Peach Schnapps', 2, 'bottles', null, 350),
  ('Bar', 'Liqueurs & mixers', 'Blue Curacao', 2, 'bottles', null, 360),
  ('Bar', 'Liqueurs & mixers', 'Buttershots', 2, 'bottles', null, 370),
  ('Bar', 'Liqueurs & mixers', 'Kahlua', 2, 'bottles', null, 380),
  ('Bar', 'Draft kegs', 'Kona Big Wave', 1, 'reserve keg', null, 390),
  ('Bar', 'Draft kegs', 'Mango Cart', 1, 'reserve keg', null, 400),
  ('Bar', 'Draft kegs', 'Space Dust', 1, 'reserve keg', null, 410),
  ('Bar', 'Draft kegs', 'AmberBock', 1, 'reserve keg', null, 420),
  ('Bar', 'Draft kegs', 'Stella Artois', 1, 'reserve keg', null, 430),
  ('Bar', 'Draft kegs', 'Dunkel', 1, 'reserve keg', null, 440),
  ('Bar', 'Wine & mead', 'House red', 3, 'reserve bottles', null, 450),
  ('Bar', 'Wine & mead', 'House white', 3, 'reserve bottles', null, 460),
  ('Bar', 'Wine & mead', 'Pinot Grigio', 3, 'reserve bottles', null, 470),
  ('Bar', 'Wine & mead', 'Vivace', 3, 'reserve bottles', null, 480),
  ('Bar', 'Wine & mead', 'Sauvignon Blanc', 3, 'reserve bottles', null, 490),
  ('Bar', 'Wine & mead', 'Mead', 3, 'reserve bottles', null, 500),
  ('Bar', 'Beer', 'Bud Light', 1, 'case', null, 510),
  ('Bar', 'Beer', 'Budweiser', 1, 'case', null, 520),
  ('Bar', 'Beer', 'Twisted Tea', 1, 'case', null, 530),
  ('Bar', 'Beer', 'Guinness', 1, 'case', null, 540),
  ('Coffee', 'Coffee beans', 'Whole bean coffee', 1, 'reserve bag', 'Walmart', 10),
  ('Coffee', 'Coffee beans', 'Whole bean decaf', 1, 'reserve', 'Walmart', 20),
  ('Coffee', 'Syrups', 'SF mocha', 0.5, 'bottle', 'Finicky Fox', 30),
  ('Coffee', 'Syrups', 'SF caramel', 0.5, 'bottle', 'Finicky Fox', 40),
  ('Coffee', 'Syrups', 'SF vanilla', 0.5, 'bottle', 'Finicky Fox', 50),
  ('Coffee', 'Syrups', 'SF coconut', null, null, 'Finicky Fox', 60),
  ('Coffee', 'Syrups', 'Torani coconut', null, null, 'Finicky Fox', 70),
  ('Coffee', 'Syrups', 'Knox mocha', 0.5, 'bottle', 'Knox', 80),
  ('Coffee', 'Syrups', 'Knox caramel', 0.5, 'bottle', 'Knox', 90),
  ('Coffee', 'Syrups', 'Knox vanilla', 0.5, 'bottle', 'Knox', 100),
  ('Coffee', 'Cups & stickers', 'Iced cups', 2, 'sleeves', null, 110),
  ('Coffee', 'Cups & stickers', 'Hot cups', 2, 'sleeves', null, 120),
  ('Coffee', 'Cups & stickers', 'Cup sleeves', 1, 'sleeve', null, 130),
  ('Coffee', 'Cups & stickers', 'Stickers', 1, 'sheet', 'Mary?', 140),
  ('Coffee', 'Milk & cream', 'Milk', 2, 'reserve', 'Walmart', 150),
  ('Coffee', 'Milk & cream', 'Oat milk', 1, 'reserve', 'Walmart', 160),
  ('Coffee', 'Milk & cream', 'Almond milk', 1, 'reserve', 'Walmart', 170),
  ('Coffee', 'Milk & cream', 'Whipped Cream', 1, 'reserve', 'Walmart', 180),
  ('Coffee', 'Milk & cream', 'Heavy Whipping Cream', 1, 'reserve', 'Walmart', 190),
  ('Coffee', 'Sweeteners', 'Honey', 1, 'reserve', 'Walmart', 200),
  ('Coffee', 'Sweeteners', 'Sugar', 0.25, 'bag', 'Walmart', 210),
  ('Coffee', 'Sweeteners', 'Brown sugar', 0.25, 'bag', 'Walmart', 220),
  ('Supplies', 'Cleaning', 'Peroxide spray', null, null, null, 10),
  ('Supplies', 'Cleaning', 'Glass cleaner', null, null, null, 20),
  ('Supplies', 'Cleaning', 'Air freshener', null, null, null, 30)
) as v(area, section, name, par_qty, unit, source, sort_order)
where not exists (select 1 from par_items);

insert into shift_tasks (title, timing, sort_order)
select * from (values
  ('Thaw pizza dough', 'opening', 10),
  ('Wipe down tables', 'closing', 20),
  ('Sweep behind the bar', 'closing', 30),
  ('Mop the bathroom', 'closing', 40)
) as v(title, timing, sort_order)
where not exists (select 1 from shift_tasks);

insert into reminders (kind, message, minutes)
select * from (values
  ('before_screening', 'Check the movie', 5),
  ('schedule_low', 'Update the schedule', 7)
) as v(kind, message, minutes)
where not exists (select 1 from reminders);
